error: Fix segfault on missing field in error stack structure (bug #67143).
* libinterp/corefcn/error.cc (Ferror): Check for required and optional fields
in stack structure. Add some self-tests.